### ISSUE TITLE
U6 promoter for gRNA

### ISSUE THREAD

**Issue by bionicles** [bionicles/coronavirus#11]
Need plasmid design ASAP before fancy shit

>R1LP2N.1 u6-promoter
AAGGTCGGGCAGGAAGAGGGCCTATTTCCCATGATTCCTTCATATTTGCATATACGATAC
AAGGCTGTTAGAGAGATAATTAGAATTAATTTGACTGTAAACACAAAGATATTAGTACAA
AATACGTGACGTAGAAAGTAATAATTTCTTGGGTAGTTTGCAGTTTTAAAATTATGTTTT
AAAATGGACTATCATATGCTTACCGTAACTTGAAAGTATTTCGATTTCTTGGCTTTATAT
ATCTTGTGGAAAGGACGAAACACC

**Comment by 5l1v3r1** [comment]
https://www.addgene.org/44251/
